---
fckeditor: 
  homeable: false
  required: false
  preferences: 
    fckeditor_debug: n
    fckeditor_toolbars: Bitweaver
  version: 0.0.0
  description: >
    FCKEditor is a 'What You See Is What You
    Get' textarea HTML editor. It works with
    IE 5.5+, Firefox 1.0+, Mozilla 1.3+, and
    Netscape 7+. 
  license: 
    name: LGPL
    description: Licensed under the GNU LESSER GENERAL PUBLIC LICENSE.
    url: http://www.gnu.org/copyleft/lesser.html 
